#!/bin/sh

set -ex

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="statsd-injector-certs"
mkdir -p ${depot_path}

# CA to distribute to loggregator certs
certstrap --depot-path ${depot_path} init --passphrase '' --common-name loggregatorCA
mv -f ${depot_path}/loggregatorCA.crt ${depot_path}/loggregator-ca.crt
mv -f ${depot_path}/loggregatorCA.key ${depot_path}/loggregator-ca.key

# Statsd-Injector certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name statsd-injector
certstrap --depot-path ${depot_path} sign statsd-injector --CA loggregator-ca

# Metron certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name metron
certstrap --depot-path ${depot_path} sign metron --CA loggregator-ca
